apiVersion: v1
kind: Service
metadata:
  name: gateway-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: gateway
    tier: datascience
  ports:
    - port: 80
      targetPort: 3000